aion/urls.py
from django.conf.urls import url
from django.contrib import admin

urlpatterns = [
    url(r'^admin/', admin.site.urls),
]

# Use include() to add URLS from the application 
from django.conf.urls import include

urlpatterns += [
    url(r'^labreserve/', include('labreserve.urls')),
]

# Add Django site authentication urls (for login, logout, password management)
from django.contrib.auth import views as auth_views

urlpatterns += [
    # The redirect here sends users back to home if they're already logged in
    # https://stackoverflow.com/questions/2320581/django-redirect-logged-in-users-from-login-page
    url(r'^accounts/',
        auth_views.LoginView.as_view(redirect_authenticated_user=True),
        name='login'),
    url(r'^logout/$', auth_views.logout, {'next_page': '/'}, name='logout'),
]

# Use static() to add url mapping to serve static files during development (only)
from django.conf import settings
from django.conf.urls.static import static

urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

# Add URL maps to redirect the base URL to our application
from django.views.generic import RedirectView

urlpatterns += [
    url(r'^$', RedirectView.as_view(url='/labreserve/', permanent=True)),
]

# Social Auth Google Verification
from django.views.generic.base import TemplateView
urlpatterns += [
    url(r'^google8ee263e74869302f.html', TemplateView.as_view(template_name='google8ee263e74869302f.html'), name="google8ee263e74869302f"),
]

from django.conf import settings
from django.conf.urls.static import static

urlpatterns += [
    url(r'^account/', include('social_django.urls', namespace='social')),
    url(r'^account/', include('django.contrib.auth.urls', namespace='auth')),
]

labreserve/urls.py
from django.conf.urls import include, url

from . import views

urlpatterns = [
    # ex: labreserve/
    #url(r'^$', views.home, name='home'),
    url(r'^$', views.index, name='index'),
    # URL to manage bookings
    url(r'bookings/manage/$', views.manageBookings, name='booking_manage'),
    # URL for Room-Based Calendar View
    url(r'^room/(?P<room>\d+)/(?P<year>[0-9]{4})/(?P<month>[0-9]{2})/(?P<day>[0-9]{2})/$', views.room_view, name='room'),
]

# URLS for Rooms (Using Model Forms)
urlpatterns += [ 
    url(r'^rooms/$', views.RoomListView.as_view(), name='rooms'),
    url(r'^rooms/(?P<pk>\d+)$', views.RoomDetailView.as_view(), name='room-detail'),
    url(r'^rooms/create/$', views.RoomCreate.as_view(), name='room_create'),
    url(r'^rooms/(?P<pk>\d+)/update/$', views.RoomUpdate.as_view(), name='room_update'),
    url(r'^rooms/(?P<pk>\d+)/delete/$', views.RoomDelete.as_view(), name='room_delete'),
]

# URLS for Bookings (Using Model Forms)
urlpatterns += [
    url(r'bookings/$', views.BookingListView.as_view(), name='bookings'),
    url(r'^bookings/(?P<pk>\d+)$', views.BookingDetailView.as_view(), name='booking-detail'),
    url(r'^bookings/create/$', views.BookingCreate.as_view(), name='booking_create'),
    url(r'^bookings/(?P<pk>\d+)/update/$', views.BookingUpdate.as_view(), name='booking_update'),
    url(r'^bookings/(?P<pk>\d+)/delete/$', views.BookingDelete.as_view(), name='booking_delete'),
    # New Booking from Calendar View
    url(r'^bookings/new/$', views.BookingCreateFromCal.as_view(), name='booking_create_from_cal'),
]

# Google Auth URLS ===========================================================
urlpatterns += [
    url(r'^profile/$', views.update_profile, name='edit-profile'),
    # url(r'^profile/(?P<pk>\d+)/$', views.ProfileDetailView.as_view(), name='view-profile'),
    url(r'^account/logout/$', views.Logout),
    url(r'^user/(?P<user_id>\d+)/$', views.userDetailView, name='view-profile'),
]

labreserve/models.py
# -*- coding: utf-8 -*-
from __future__ import unicode_literals

from django.db import models

import datetime
from datetime import date
from django.contrib.auth.models import User

from django.urls import reverse #Used to generate URLs by reversing the URL patterns

# Create your models here.
class Room(models.Model):
    room_text = models.CharField(max_length=10)
    room_no_of_computers = models.IntegerField(default=0)
    room_description = models.CharField(max_length=200)
    room_has_projector = models.BooleanField(default=False)
    class Meta:
        permissions = (('room_admin', 'Can Add, Edit, Delete Rooms'),)
        
    def __str__(self):
        return self.room_text
        
    # Returns the url to access a particular room instance.
    def get_absolute_url(self):
        return reverse('room-detail', args=[str(self.id)])
        

class Booking(models.Model):
    periods = ( 
        (1, '1st Period'), 
        (2, '2nd Period'), 
        (3, '3rd Period'),
        (4, '4th Period'),
        (5, '5th Period'),
        (6, '6th Period'),
        (7, '7th Period'),
        (8, '8th Period'),
    )

    room = models.ForeignKey(Room, on_delete=models.CASCADE)
    booking_owner = models.ForeignKey(User)
    booking_date = models.DateField(('Reservation Date'))#, default=date.today )
    booking_client = models.CharField(('Reserved For'), max_length=200)
    booking_period = models.IntegerField(('Period'), choices=periods, default=1)
    
    # Prevent double booking a room on the same date / period
    class Meta:
        unique_together = [
            ("booking_date", "booking_period", "room")
        ]
        # default_permissions = ('add', 'change', 'delete', 'view')
    
    # Returns the url to access a particular Booking instance.
    def get_absolute_url(self):
        return reverse('booking-detail', args=[str(self.id)])   
    
    def __str__(self):
        description = 'Reserved for %s, by %s.' % (self.booking_client, self.booking_owner)
        return description
        
# Google Auth Models
from django.db import models
from django.contrib.auth.models import User
from django.db.models.signals import post_save
from django.dispatch import receiver
class Profile(models.Model):
    user = models.OneToOneField(User,unique=True, null=False, db_index=True)
    bio = models.TextField(max_length=500, blank=True)
    location = models.CharField(max_length=30, blank=True)
    phone = models.CharField(max_length=30, blank=True)
    room_no = models.CharField(max_length=30, blank=True)


@receiver(post_save, sender=User)
def create_user_profile(sender, instance, created, **kwargs):
    if created:
        Profile.objects.create(user=instance)

@receiver(post_save, sender=User)
def save_user_profile(sender, instance, **kwargs):
    instance.profile.save()

labreserve/forms.py
from django.shortcuts import redirect, HttpResponseRedirect
from django.contrib.auth import logout
from django.contrib.auth.models import User
from labreserve.models import Profile
from django import forms
class UserForm(forms.ModelForm):
    class Meta:
        model = User
        fields = ('first_name', 'last_name', 'email')
class ProfileForm(forms.ModelForm):
    class Meta:
        model = Profile
        fields = ('bio','location', 'phone', 'room_no')

labreserve/views.py
# -*- coding: utf-8 -*-
from __future__ import unicode_literals

import datetime

from django.shortcuts import render
from .models import Booking, Room
from django.shortcuts import get_object_or_404


# Landing page for  Aion  
def index( request ):
    todays_booking_list = Booking.objects.filter( booking_owner = request.user.pk ).filter( booking_date__gte = datetime.date.today().strftime("%Y-%m-%d") )
    context = { 
      'todays_booking_list': todays_booking_list,
    }

    return render( request, 'aion/index.html', context )
    

#===============================================================================
# Generic ViewForms for Room
# (No Form.py required for these. Direct View to Template)
from django.views.generic.edit import CreateView, UpdateView, DeleteView
from django.urls import reverse_lazy
from django.contrib.auth.mixins import PermissionRequiredMixin
from django.contrib.auth.decorators import permission_required
from django.contrib.auth.decorators import login_required
from django.utils.decorators import method_decorator

@method_decorator(login_required, name='dispatch')
class RoomCreate(PermissionRequiredMixin, CreateView):
    permission_required = 'room.room_admin'
    model = Room
    fields = '__all__'
    
@method_decorator(login_required, name='dispatch')
class RoomUpdate(PermissionRequiredMixin, UpdateView):
    permission_required = 'room.room_admin'
    model = Room
    fields = '__all__'
    
@method_decorator(login_required, name='dispatch')
class RoomDelete(PermissionRequiredMixin, DeleteView):
    permission_required = 'room.room_admin'
    model = Room
    success_url = reverse_lazy('rooms') 

from django.views import generic

# Generic List view for Rooms
@method_decorator(login_required, name='dispatch')
class RoomListView(generic.ListView):
    model=Room
    paginate_by=5
    
# Generic Model View for Room
@method_decorator(login_required, name='dispatch')
class RoomDetailView(generic.DetailView):
    model=Room

#===============================================================================
# Generic ViewForms for Bookings
@method_decorator(login_required, name='dispatch')
class BookingCreate(CreateView):
    model = Booking
    fields = '__all__'

from django.http import HttpResponseForbidden
@method_decorator(login_required, name='dispatch')
class BookingUpdate(UpdateView):
    model = Booking
    fields = '__all__'
    
    # https://stackoverflow.com/questions/11225704/how-to-restrict-editing-of-records-to-the-logged-in-user/11226230#11226230
    def dispatch(self, request, *args, **kwargs):
      handler = super(BookingUpdate, self).dispatch(request, *args, **kwargs)
      # Only allow editing if current user is owner
      
      if self.object.booking_owner != request.user and not request.user.is_superuser:
          return HttpResponseForbidden(u"You do not have permissions to update this reservation.")
      
      return handler

@method_decorator(login_required, name='dispatch')
class BookingDelete(DeleteView):
    model = Booking
    success_url = reverse_lazy('bookings')
    
    def dispatch(self, request, *args, **kwargs):
      handler = super(BookingDelete, self).dispatch(request, *args, **kwargs)
      # Only allow if current user is owner
      if self.object.booking_owner != request.user:
          return HttpResponseForbidden(u"You do not have permissions to delete this reservation.")
      return handler

# Generic List view for Bookings
@method_decorator(login_required, name='dispatch')
class BookingListView(generic.ListView):
    model=Booking
    paginate_by=5
    
# Generic Model View for Booking
@method_decorator(login_required, name='dispatch')
class BookingDetailView(generic.DetailView):
    model=Booking
    
# Create new Booking from Calendar
@method_decorator(login_required, name='dispatch')
class BookingCreateFromCal(CreateView):
    model=Booking 
    fields='__all__'
    
    # This makes the view request a 
    # different template from the other BookingCreate class
    template_name_suffix='_create_form' 

# View to manage Bookings with pagination
from django.core.paginator import Paginator, EmptyPage, PageNotAnInteger
@login_required
def manageBookings(request):
    booking_list = Booking.objects.filter( booking_owner = request.user ) #Booking.objects.all()
    paginator = Paginator(booking_list, 10)
    page = request.GET.get('page', 1)
    try:
      bookings = paginator.page(page)
    except PageNotAnInteger:
      bookings = paginator.page(1)
    except EmptyPage:
      bookings = paginator.page(paginator.num_pages)
      
    return render(request, 'labreserve/booking_manage.html', {'bookings': bookings})

# View Calendar by Room ========================================================
from django.db.models import Q

@login_required
def room_view( request, room, year, month, day ):
  
  lab_room = get_object_or_404( Room, pk=room )
  
  requested_date = datetime.datetime.strptime( year+month+day, "%Y%m%d" ).date()
  
  monday = requested_date + datetime.timedelta(days=-requested_date.weekday(), weeks=0)
  tuesday = monday + datetime.timedelta(days=+1)
  wednesday = tuesday + datetime.timedelta(days=+1)
  thursday = wednesday + datetime.timedelta(days=+1)
  friday = thursday + datetime.timedelta(days=+1)
  prev_week = monday + datetime.timedelta(days=-7)
  next_week = monday + datetime.timedelta(days=+7)
  
  booking_list = Booking.objects.filter( Q(room=lab_room),Q(booking_date__gte = monday), Q(booking_date__lte = friday) )
  
  context = { 
    'room': room,
    'room_name': lab_room,
    'monday': monday, 
    'tuesday': tuesday, # start_date + relativedelta(days=5)
    'wednesday': wednesday,
    'thursday': thursday,
    'friday': friday,
    'prev_week': prev_week.strftime("%Y/%m/%d"),
    'next_week': next_week.strftime("%Y/%m/%d"),
    'booking_list' : booking_list,
  }
  
  return render( request, 'labreserve/room.html', context )

# Google Auth Views ============================================================
from django.shortcuts import render, get_object_or_404, redirect
from django.core.paginator import Paginator, EmptyPage, PageNotAnInteger
from django.contrib.auth.decorators import login_required
from django.contrib.auth.models import User
from django.contrib.auth import logout
from django.http import HttpResponseRedirect
from django.db import transaction
from .models import Profile
from .forms import UserForm,ProfileForm

# @login_required
# def Home(request):
#     return render(request, 'home/home.html')

@login_required
@transaction.atomic
def update_profile(request):
    if request.method == 'POST':
        user_form = UserForm(request.POST, instance=request.user)
        profile_form = ProfileForm(request.POST, instance=request.user.profile)
        if user_form.is_valid() and profile_form.is_valid():
            user_form.save()
            profile_form.save()
            return HttpResponseRedirect('/')
        else:
            messages.error(request, _('Please correct the error below.'))
    else:
        user_form = UserForm(instance=request.user)
        profile_form = ProfileForm(instance=request.user.profile)
    return render(request, 'labreserve/profile_form.html', {
        'user_form': user_form,
        'profile_form': profile_form
    })
def Logout(request):
    logout(request)
    return HttpResponseRedirect('/')
    
# Generic Model View for Profiles
# @method_decorator(login_required, name='dispatch')
# class ProfileDetailView(generic.DetailView):
#     model=Profile

# Use this view to see info about who has booked a room
@login_required
def userDetailView(request, user_id):
  user = User.objects.get(pk=user_id)
  context={ 'user' : user }
  return render(request, 'labreserve/user_detail.html', context)

labreserve/templates/labreserve/booking_confirm_delete.html
{% extends "base.html" %}

{% block title %} | Delete{% endblock %}

{% block content %}

<h1>Delete Reservation</h1>

<p>Are you sure you want to delete this reservation?</p>

<p>{{ booking }}</p>

<form action="" method="POST">
  {% csrf_token %}
  <div class="form-btn">
    <button type="submit" class="btn btn-danger">Yes, delete.</button>
  </div>
</form>

{% endblock %}

labreserve/templates/labreserve/booking_create_form.html
{% extends "base.html" %}

{% block title %} | New{% endblock %}

{% block content %}
{% load widget_tweaks %}
<form action="" method="post">
  {% csrf_token %}
    
  {{ form.non_field_errors }}
  
  <div class="fieldWrapper form-group">
    {{ form.room.errors }}
    <label for="{{ form.room.id_for_label }}">Room:</label>
    <select id="id_room" name="room" class="form-control">
      {% for x,y in form.fields.room.choices %}
        <option value="{{ x }}"{% if request.GET.room == x|stringformat:"i" %} selected{% endif %}>{{ y }}</option>
      {% endfor %}
    </select>
  </div>
  
  <div class="fieldWrapper form-group">
    {{ form.booking_owner.errors }}
    <label for="{{ form.booking_owner.id_for_label }}">Reserved By:</label>
    <select id="id_booking_owner" name="booking_owner" class="form-control">
      {% for x,y in form.fields.booking_owner.choices %}
        <option value="{{ x }}"{% if request.user.id == x %} selected{% endif %}>{{ y }}</option>
      {% endfor %}
    </select>
  </div>
  
  <div class="fieldWrapper form-group">
    {{ form.booking_date.errors }}
    <label for="{{ form.booking_date.id_for_label }}">Reservation Date:</label>
    <input type="text" 
      name="booking_date" 
      required="" 
      class="form-control" 
      value="{{ request.GET.month }}/{{ request.GET.day }}/{{ request.GET.year }}" id="id_booking_date">
  </div>
  <div class="fieldWrapper form-group">
    {{ form.booking_client.errors }}
    <label for="{{ form.booking_date.id_for_label }}">Reserved For:</label>
    {{ form.booking_client|add_class:'form-control' }}
  </div>
  
  <div class="fieldWrapper form-group">
    {{ form.booking_period.errors }}
    <label for="{{ form.booking_period.id_for_label }}">Period:</label>
    <select id="id_booking_period" name="booking_period" class="form-control">
      {% for x,y in form.fields.booking_period.choices %}
        <option value="{{ x }}"{% if request.GET.period == x|stringformat:"i" %} selected{% endif %}>{{ y }}</option>
      {% endfor %}
    </select>
  </div>
    

  <div class="form-btn">
    <button type="submit" class="btn btn-primary">Submit</button>
  </div>

    
</form>
{% endblock %}

labreserve/templates/labreserve/booking_detail.html
{% extends "base.html" %}
{% block title %} | Detail{% endblock %}

{% block content %}
<h2>Booking</h2>
<div class="row">
      <div class="col"> 
    <div class="table-responsive">
    <table class="table">
      <thead>
        <th scope="col">Room</th>
        <th scope="col">Owner</th>
        <th scope="col">Date</th>
        <th scope="col">Period</th>
        <th scope="col">Reserved For</th>
        <th scope="col">Manage</th>
      </thead>
      <tbody>
        <tr>
          <td>{{ booking.room }}</td>
          <td><a href="{% url 'view-profile' booking.booking_owner.id %}" title="View User Profile">{{ booking.booking_owner }}</a></td>
          <td>{{ booking.booking_date }}</td>
          <td>{{ booking.booking_period }}</td>
          <td><a href="{{ booking.get_absolute_url }}">{{ booking.booking_client }}</a></td>
          <td class="booking-controls">
            <a class="btn btn-sm btn-primary" href="{{ booking.get_absolute_url }}/update/">Edit</a>
            <a class="btn btn-sm btn-danger" href="{{ booking.get_absolute_url }}/delete/">Delete</a>
          </td>
        </tr>
      </tbody>
    </table>
    </div>
    </div></div>
{% endblock %}

labreserve/templates/labreserve/booking_form.html
{% extends "base.html" %}

{% block title %} | New {% endblock %}

{% block content %}
{% load widget_tweaks %}
<div class="row">
  <div class="col"> 
<form action="" method="post">
  {% csrf_token %}
    
  {{ form.non_field_errors }}
  
  <div class="fieldWrapper form-group">
    {{ form.booking_owner.errors }}
    <label for="{{ form.booking_owner.id_for_label }}">Reserved By:</label>
    <select id="id_booking_owner" name="booking_owner" class="form-control">
      {% if user.is_superuser %}
        {% for x,y in form.fields.booking_owner.choices %}
          <option value="{{ x }}"{% if request.user.id == x %} selected{% endif %}>{{ y }}</option>
        {% endfor %}
      {% else %}
        {% for x,y in form.fields.booking_owner.choices %}
          {% if request.user.id == x %}
            <option value="{{ x }}"selected>{{ y }}</option>
          {% endif %}
        {% endfor %}
      {% endif %}
    </select>
  </div>
  
  <div class="fieldWrapper form-group">
    {{ form.room.errors }}
    <label for="{{ form.room.id_for_label }}">Room:</label>
    {{ form.room|add_class:'form-control' }}
  </div>
  
    <div class="fieldWrapper form-group">
    {{ form.booking_date.errors }}
    <label for="{{ form.booking_date.id_for_label }}">Reservation Date:</label>
    <input type="text" 
      name="booking_date" 
      required="" 
      class="form-control" 
      value="{% now 'm/d/Y' %}" id="id_booking_date">
  </div>
  
  <div class="fieldWrapper form-group">
    {{ form.booking_client.errors }}
    <label for="{{ form.booking_date.id_for_label }}">Reserved For:</label>
    {{ form.booking_client|add_class:'form-control' }}
  </div>
  
  <div class="fieldWrapper form-group">
    {{ form.booking_period.errors }}
    <label for="{{ form.booking_period.id_for_label }}">Period:</label>
    {{ form.booking_period|add_class:'form-control' }}
  </div>
    
  <div class="form-btn">
    <button type="submit" class="btn btn-primary">Submit</button>
  </div>
</div></div>
    
</form>
{% endblock %}

labreserve/templates/labreserve/booking_list.html
{% extends "base.html" %}

{% block title %} | All{% endblock %}

{% block content %}
  <h2>All Reservations</h2>

  {% if booking_list %}
  <div class="row">
      <div class="col"> 
    <div class="table-responsive">
    <table class="table">
      <thead>
        <tr>
        <th scope="col">Room</th>
        <th scope="col">Owner</th>
        <th scope="col">Date</th>
        <th scope="col">Period</th>
        <th scope="col">Reserved For</th>
        <th scope="col">Manage</th>
        </tr>
      </thead>
      <tbody>
      {% for booking in booking_list %}
        <tr>
          <td>{{ booking.room }}</td>
          <td><a href="{% url 'view-profile' booking.booking_owner.id %}" title="View User Profile">{{ booking.booking_owner }}</a></td>
          <td>{{ booking.booking_date }}</td>
          <td>{{ booking.booking_period }}</td>
          <td><a href="{{ booking.get_absolute_url }}">{{ booking.booking_client }}</a></td>
          <td class="booking-controls">
            <a class="btn btn-sm btn-primary" href="{{ booking.get_absolute_url }}/update/">Edit</a>
            <a class="btn btn-sm btn-danger" href="{{ booking.get_absolute_url }}/delete/">Delete</a>
          </td>
        </tr>
      {% endfor %}
      </tbody>
    </table>
    </div>
    </div></div>
    {% else %}
      <p>There are no reservations in the system.</p>
    {% endif %}
    
  {% if is_paginated %}
    <nav aria-label="Page navigation">
      <ul class="pagination">
      <!--span class="step-links"-->
        {% if page_obj.has_previous %}
          <li class="page-item">
            <a class="page-link" href="?page=1">&laquo; first</a>
          </li>
          <li class="page-item">
            <a class="page-link" href="?page={{ page_obj.previous_page_number }}">previous</a>
          </li>
        {% endif %}
  
        <!--<span class="current">-->
          <li class="page-item active">
            <span class="page-link">
              Page {{ page_obj.number }} of {{ page_obj.paginator.num_pages }}
            </span>
          </li>
        <!--</span>-->

        {% if page_obj.has_next %}
          <li class="page-item">
            <a class="page-link" href="?page={{ page_obj.next_page_number }}">next</a>
          </li>
          <li class="page-item">
            <a class="page-link" href="?page={{ page_obj.paginator.num_pages }}">last &raquo;</a>
          </li>
        {% endif %}
      <!--</span>-->
    </ul>
  </nav>
  {% endif %}
  
{% endblock %}

labreserve/templates/labreserve/booking_manage.html
{% extends "base.html" %}

{% block title %} | Manage{% endblock %}

{% block content %}
<div class="row">
  <div class="col"> 
    <h1>All Reservations</h1>
</div></div>

    {% if bookings %}
    <div class="row">
      <div class="col"> 
    <div class="table-responsive">
    <table class="table">
      <thead>
        <tr>
        <th scope="col">Room</th>
        <th scope="col">Owner</th>
        <th scope="col">Date</th>
        <th scope="col">Period</th>
        <th scope="col">Reserved For</th>
        <th scope="col">Manage</th>
        </tr>
      </thead>
      <tbody>
      {% for booking in bookings %}
        <tr>
          <td>{{ booking.room }}</td>
          <td><a href="{% url 'view-profile' booking.booking_owner.id %}" title="View User Profile">{{ booking.booking_owner }}</a></td>
          <td>{{ booking.booking_date }}</td>
          <td>{{ booking.booking_period }}</td>
          <td><a href="{{ booking.get_absolute_url }}">{{ booking.booking_client }}</a></td>
          <td class="booking-controls">
            <a class="btn btn-sm btn-primary" href="{{ booking.get_absolute_url }}/update/">Edit</a>
            <a class="btn btn-sm btn-danger" href="{{ booking.get_absolute_url }}/delete/">Delete</a>
          </td>
        </tr>
      {% endfor %}
      </tbody>
    </table>
    </div>
    </div></div>
    {% else %}
      <p>You have no reservations in the system.</p>
    {% endif %}
<div class="row">
  <div class="col"> 
  
  <nav aria-label="Page navigation">
    <ul class="pagination">
      <!--span class="step-links"-->
        {% if bookings.has_previous %}
          <li class="page-item">
            <a class="page-link" href="?page=1">&laquo; first</a>
          </li>
          <li class="page-item">
            <a class="page-link" href="?page={{ bookings.previous_page_number }}">previous</a>
          </li>
        {% endif %}
  
        <!--<span class="current">-->
          <li class="page-item active">
            <span class="page-link">
              Page {{ bookings.number }} of {{ bookings.paginator.num_pages }}
            </span>
          </li>
        <!--</span>-->
  
        {% if bookings.has_next %}
          <li class="page-item">
            <a class="page-link" href="?page={{ bookings.next_page_number }}">next</a>
          </li>
          <li class="page-item">
            <a class="page-link" href="?page={{ bookings.paginator.num_pages }}">last &raquo;</a>
          </li>
        {% endif %}
      <!--</span>-->
    </ul>
  </nav>
</div></div>
{% endblock %}

labreserve/templates/labreserve/profile_detail.html
{% extends "base.html" %}
{% block title %} | Detail{% endblock %}

{% block content %}
  <h3>User Info</h3>
  <small><strong>Username:</strong> {{ profile.user }}</small>
  
  <p><strong>Name:</strong> {{ profile.user.first_name }} {{ profile.user.last_name }}</p>
  <p><strong>Email:</strong> {{ profile.user.email }}</p>
  <p><strong>Location:</strong> {{ profile.location }}</p>
  <p><strong>Bio:</strong> {{ profile.bio }}</p>


{% endblock %}

labreserve/templates/labreserve/profile_form.html
{% extends "base.html" %}
{% load widget_tweaks %}

{% block title %} | Profile{% endblock %}

{% block content %}

<form action="" method="post">
  {% csrf_token %}
  <div class="fieldWrapper form-group">
    {{ user_form.first_name.errors }}
    <label for="{{ user_form.first_name.id_for_label }}">First Name:</label>
    {{ user_form.first_name|add_class:'form-control' }}
  </div>
  
  <div class="fieldWrapper form-group">
    {{ user_form.last_name.errors }}
    <label for="{{ user_form.last_name.id_for_label }}">Last Name:</label>
    {{ user_form.last_name|add_class:'form-control' }}
  </div>
  
  <div class="fieldWrapper form-group">
    {{ user_form.email.errors }}
    <label for="{{ user_form.email.id_for_label }}">Email:</label>
    {{ user_form.email|add_class:'form-control' }}
  </div>
  
  <div class="fieldWrapper form-group">
    {{ profile_form.location.errors }}
    <label for="{{ profile_form.location.id_for_label }}">Location:</label>
    {{ profile_form.location|add_class:'form-control' }}
  </div>
  
  <div class="fieldWrapper form-group">
    {{ profile_form.phone.errors }}
    <label for="{{ profile_form.phone.id_for_label }}">Phone:</label>
    {{ profile_form.phone|add_class:'form-control' }}
  </div>
  
  <div class="fieldWrapper form-group">
    {{ profile_form.room_no.errors }}
    <label for="{{ profile_form.room_no.id_for_label }}">Classroom:</label>
    {{ profile_form.room_no|add_class:'form-control' }}
  </div>
  
  <div class="fieldWrapper form-group">
    {{ profile_form.bio.errors }}
    <label for="{{ profile_form.bio.id_for_label }}">Bio:</label>
    {{ profile_form.bio|add_class:'form-control' }}
  </div>

  
  <div class="form-btn">
    <button type="submit" class="btn btn-primary">Submit</button>
  </div>
    
</form>
{% endblock %}